<a href="https://colab.research.google.com/github/rachelhakes/Capstone-Project/blob/main/Image_Training_Testing_Checks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive


In [ ]:
# some_file.py
import sys

# insert at 1, 0 is the script path (or '' in REPL)
sys.path.insert(1, '/content/gdrive/MyDrive/Project/LDL/code')

In [ ]:
import numpy as np
from utils.report import report_precision_se_sp_yi, report_mae_mse
import pandas as pd

In [ ]:
# fix the indexing by 1

In [ ]:
test_data = np.loadtxt('/content/gdrive/MyDrive/Project/Detection/VOC2007/ImageSets/Main/NNEW_test_1.txt', dtype='str')

In [ ]:
test_data.shape

(292, 3)

In [ ]:
test_data_df = pd.DataFrame(test_data)

In [ ]:
test_data_df.columns = ['filename', 'class', 'counts']
test_data_df

filename class counts
0     levle0_60.jpg     0      1
1    levle0_483.jpg     0      2
2    levle0_110.jpg     0      2
3    levle0_404.jpg     0      1
4    levle0_155.jpg     0      1
..              ...   ...    ...
287   levle3_37.jpg     3     55
288  levle3_109.jpg     3     52
289   levle3_76.jpg     3     56
290  levle3_113.jpg     3     64
291   levle3_30.jpg     3     53

[292 rows x 3 columns]

In [ ]:
test_data_df = test_data_df[:-1]
test_data_df

filename class counts
0     levle0_60.jpg     0      1
1    levle0_483.jpg     0      2
2    levle0_110.jpg     0      2
3    levle0_404.jpg     0      1
4    levle0_155.jpg     0      1
..              ...   ...    ...
286   levle3_83.jpg     3     51
287   levle3_37.jpg     3     55
288  levle3_109.jpg     3     52
289   levle3_76.jpg     3     56
290  levle3_113.jpg     3     64

[291 rows x 3 columns]

In [ ]:
y_true = np.array([int(t[1]) for t in test_data][:-1])
y_true

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3])

In [ ]:
y_count_true = np.array([int(t[2]) for t in test_data][:-1])
y_count_true

array([ 1,  2,  2,  1,  1,  1,  3,  1,  1,  1,  2,  1,  1,  2,  4,  3,  3,
        2,  2,  2,  2,  3,  3,  1,  2,  2,  4,  3,  5,  1,  2,  2,  4,  1,
        3,  3,  2,  2,  4,  2,  2,  1,  2,  2,  2,  3,  1,  1,  3,  2,  3,
        2,  3,  2,  3,  2,  1,  1,  1,  1,  1,  2,  2,  1,  2,  1,  2,  1,
        2,  1,  3,  1,  3,  1,  1,  2,  2,  5,  2,  3,  3,  1,  3,  2,  3,
        4,  2,  1,  2,  1,  3,  1,  2,  1,  2,  1,  4,  1,  2,  1,  1,  1,
        2,  9,  6, 14, 10,  9, 19, 10,  7,  6, 13, 17, 12,  6, 11,  6,  6,
        8,  7,  6, 17,  9,  7,  9,  9,  9,  6, 12,  7,  7,  7,  9,  8,  7,
        7, 12, 11, 10,  6,  6,  6,  8,  8,  8,  8,  7, 10, 15,  7,  9,  8,
        8, 10,  9,  6,  6, 12, 10,  7,  7,  6,  9,  8, 10, 10, 11,  9,  8,
       10,  6,  9,  7, 11,  8,  6,  6, 17,  9,  8,  8,  6, 10,  7,  9,  9,
        8,  7,  6,  9, 10, 12,  8,  9,  6, 14,  7,  6,  7,  8,  7,  8, 14,
        8,  9, 15,  6,  8,  8, 11,  9, 14,  9,  8, 10,  8,  6,  7,  6,  7,
        7,  6, 10, 17,  6

# Load resnet152, 101, 50, and 34 image class and counts results

In [ ]:
y_preds, y_preds_count, y_preds_count2cls = np.load('/content/gdrive/MyDrive/Project/image classes and counts/counts-class-resnet152.npy', allow_pickle=True)
y_preds1, y_preds_count1, y_preds_count2cls1 = np.load('/content/gdrive/MyDrive/Project/image classes and counts/counts-class-resnet101.npy', allow_pickle=True)
y_preds2, y_preds_count2, y_preds_count2cls2 = np.load('/content/gdrive/MyDrive/Project/image classes and counts/counts-class-resnet50.npy', allow_pickle=True)
y_preds3, y_preds_count3, y_preds_count2cls3 = np.load('/content/gdrive/MyDrive/Project/image classes and counts/counts-class-resnet34.npy', allow_pickle=True)

##resnet152

In [ ]:
y_preds_values = np.array([y.item() for y in y_preds][1:])
y_preds_values

array([0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0,
       0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 2, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 0, 2, 2, 3, 2, 1, 1, 2, 2, 1, 1, 1, 1, 2,
       2, 2, 2, 1, 2, 1, 2, 1, 1, 2, 3, 2, 2, 2, 2, 2, 2, 2, 3, 2, 1, 2,
       1, 3, 3, 3, 3, 3, 3, 3, 2, 3, 3, 3, 3, 3, 2, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3])

In [ ]:
y_preds_count_values = np.array([y.item() for y in y_preds_count][1:])
y_preds_count_values

array([ 2,  0,  0,  0,  1,  5,  2,  1,  1,  3,  0,  0,  2,  6,  2,  5,  2,
        7,  5,  0,  1,  5,  0,  5,  0,  5,  0,  5,  1,  1,  2,  2,  0,  5,
        1,  2,  0,  2,  0,  0,  0,  0,  2,  2,  1,  0,  2,  1,  2,  6,  0,
        2,  1,  1,  1,  0,  0,  1,  1,  1,  2,  2,  0,  7,  0,  1,  0,  2,
        1,  5,  0,  3,  0,  1,  1,  2,  4,  3,  2,  3,  0,  1,  1,  3,  0,
        2,  0,  1,  1,  3,  3,  0,  2,  1,  0,  5,  1,  1,  0,  0,  0,  0,
        7,  3, 10,  5,  9, 13,  8,  2,  2,  9, 19, 10,  6,  8,  3,  2,  5,
        5,  6,  8,  8,  5,  8,  6,  7,  8, 19,  6,  5,  5,  6,  8,  7,  5,
        9,  6,  7,  7,  5,  0,  8, 20,  6,  8,  8,  7, 13,  7,  5,  9,  6,
       12,  8,  5,  7, 13, 10,  7,  2,  7,  9,  7, 11,  7,  8,  5,  6, 11,
        6, 10,  8, 10,  3,  9,  7, 10,  8,  7,  8,  5,  8, 10,  7, 23,  7,
        3,  5,  9,  8, 19,  9,  6,  6,  8,  6,  3,  6,  6, 10,  8,  8,  8,
       10, 19,  4,  7,  7,  6,  6, 11,  9,  5, 19,  5,  8,  5,  2,  7,  6,
        7,  8, 10,  6,  5

In [ ]:
y_preds_count2cls_values = np.array([y.item() for y in y_preds_count2cls][1:])
y_preds_count2cls_values

array([0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0,
       0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 2, 2, 3, 2, 1, 1, 2, 2, 1, 1, 1, 1, 2,
       2, 2, 2, 2, 2, 1, 2, 1, 1, 2, 3, 2, 2, 2, 2, 2, 2, 2, 3, 2, 1, 2,
       1, 3, 3, 3, 3, 3, 3, 3, 2, 3, 3, 3, 3, 3, 2, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3])

##resnet101

In [ ]:
y_preds_values1 = np.array([y.item() for y in y_preds1][1:])
y_preds_values1

array([0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1,
       0, 1, 1, 1, 1, 0, 1, 1, 0, 2, 1, 3, 2, 1, 1, 2, 2, 1, 1, 1, 1, 2,
       2, 2, 2, 1, 2, 1, 2, 1, 1, 2, 3, 1, 2, 2, 2, 2, 1, 2, 3, 2, 1, 2,
       1, 3, 2, 3, 3, 3, 3, 3, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3])

In [ ]:
y_preds_count_values1 = np.array([y.item() for y in y_preds_count1][1:])
y_preds_count_values1

array([ 2,  0,  0,  1,  1,  5,  1,  0,  1,  2,  1,  1,  2,  6,  2,  1,  1,
        5,  1,  0,  2,  5,  0,  3,  0,  3,  1,  4,  1,  2,  6,  1,  0,  2,
        1,  2,  0,  3,  0,  0,  1,  1,  1,  1,  1,  1,  1,  1,  0,  5,  1,
        1,  1,  1,  1,  0,  1,  2,  1,  1,  1,  1,  0,  6,  1,  1,  1,  1,
        0,  4,  1,  2,  0,  1,  1,  1,  3,  1,  3,  2,  1,  1,  1,  4,  0,
        2,  1,  1,  1,  1,  3,  1,  1,  1,  1,  6,  1,  2,  0,  0,  0,  0,
        7,  2, 10,  4,  7, 13,  7,  4,  2,  8, 19, 11,  4,  7,  3,  2,  2,
        5,  7,  8,  8,  4,  7,  4,  6,  7, 13,  6,  4,  3,  5,  7,  7,  5,
        9,  5,  4,  6,  1,  0,  7, 18,  6,  8,  7,  7, 12,  7,  5,  8,  4,
       11,  7,  3,  6, 12,  8,  4,  4,  6,  7,  6,  4,  7,  8,  4,  6, 11,
        4, 10,  8, 11,  3,  9,  7, 11,  8,  6,  9,  3,  7, 10,  8,  8,  4,
        2,  3,  9,  7, 14,  8,  7,  3,  8,  6,  1,  6,  5, 11,  8, 10,  7,
        8,  9,  2,  7,  7,  6,  6,  9, 10,  3, 16,  6,  6,  6,  1,  5,  4,
        4,  9, 11,  7,  4

In [ ]:
y_preds_count2cls_values1 = np.array([y.item() for y in y_preds_count2cls1][1:])
y_preds_count2cls_values1

array([0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0,
       0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1,
       0, 1, 1, 1, 1, 0, 1, 1, 0, 2, 1, 3, 2, 1, 1, 2, 2, 1, 1, 1, 1, 2,
       2, 2, 2, 1, 2, 1, 2, 1, 1, 2, 3, 2, 2, 2, 2, 2, 1, 2, 3, 2, 1, 2,
       1, 3, 2, 3, 3, 3, 3, 3, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3])

## resnet 50

In [ ]:
y_preds_values2 = np.array([y.item() for y in y_preds2][1:])
y_preds_values2

array([0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0,
       0, 1, 2, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 2, 1, 2, 1, 1, 0, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 2, 1, 1, 0, 0, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 0, 2, 1, 3, 2, 1, 1, 2, 2, 2, 2, 1, 2, 2,
       2, 2, 2, 2, 2, 1, 2, 1, 1, 2, 3, 2, 2, 2, 2, 2, 1, 2, 3, 2, 1, 2,
       1, 3, 2, 3, 3, 2, 3, 3, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3])

In [ ]:
y_preds_count_values2 = np.array([y.item() for y in y_preds_count2][1:])
y_preds_count_values2

array([ 3,  0,  1,  0,  3,  8,  1,  1,  2,  2,  1,  1,  4,  6,  3,  2,  1,
        3,  5,  1,  1,  3,  0,  3,  0,  5,  1,  4,  2,  3,  3,  3,  1,  4,
        1,  2,  2,  3,  0,  0,  1,  1,  2,  1,  4,  1,  2,  1,  1,  5,  2,
        1,  1,  1,  2,  0,  1,  2,  5,  1,  3,  1,  1,  6,  1,  0,  1,  3,
        1,  6,  1,  3,  0,  1,  2,  2,  3,  4,  3,  4,  0,  1,  2,  6,  0,
        4,  1,  1,  2,  4,  3,  1,  4,  1,  1,  6,  1,  3,  0,  0,  0,  1,
        8,  4,  9,  6,  6, 17,  7,  2,  3,  9, 22, 11,  5,  8,  3,  1,  4,
        5,  7,  7,  7,  6,  8,  7,  8,  7, 17,  6,  4,  4,  6,  9,  7,  6,
        9,  5,  7,  8,  5,  1,  7, 18,  6,  8,  8,  7,  9,  6,  4,  8,  6,
       11,  7,  4,  7, 12, 10,  6,  3,  6,  8,  6,  4,  6,  8,  4,  5, 10,
        7, 10,  9, 11,  4,  9,  7,  9, 10,  4,  8,  6,  8,  8,  8,  7,  7,
        4,  3, 21,  7, 21,  8,  6,  3,  7,  7,  1,  7,  7,  9,  9, 12,  9,
        7, 10,  4,  7,  8,  6,  4, 10,  9,  4, 20,  6,  6,  4,  1,  6,  4,
        7, 11, 16,  6,  4

In [ ]:
y_preds_count2cls_values2 = np.array([y.item() for y in y_preds_count2cls2][1:])
y_preds_count2cls_values2

array([0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0,
       0, 1, 2, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 2, 1, 2, 1, 1, 0, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 2, 1, 1, 1, 0, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 0, 2, 1, 3, 2, 2, 1, 2, 2, 2, 2, 1, 2, 2,
       2, 2, 1, 2, 2, 2, 2, 1, 1, 2, 3, 2, 2, 2, 2, 2, 1, 2, 3, 2, 2, 2,
       1, 3, 2, 3, 3, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3])

## resnet 34

In [ ]:
y_preds_values3 = np.array([y.item() for y in y_preds3][1:])
y_preds_values3

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0,
       0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 1, 2, 1,
       1, 2, 2, 1, 2, 2, 2, 1, 1, 2, 2, 2, 2, 2, 2, 2, 1, 1, 2, 2, 2, 2,
       1, 3, 2, 3, 3, 3, 2, 3, 2, 3, 3, 3, 3, 3, 2, 3, 2, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 2])

In [ ]:
y_preds_count_values3 = np.array([y.item() for y in y_preds_count3][1:])
y_preds_count_values3

array([ 1,  1,  1,  1,  1,  3,  2,  1,  1,  2,  1,  1,  1,  6,  1,  2,  1,
        5,  2,  1,  1,  5,  0,  2,  0,  2,  1,  5,  1,  1,  2,  1,  1,  2,
        1,  1,  1,  2,  1,  1,  1,  0,  1,  1,  3,  1,  1,  1,  1,  2,  1,
        0,  1,  1,  1,  1,  1,  1,  1,  0,  2,  1,  1,  6,  1,  1,  1,  2,
        1,  5,  1,  1,  1,  1,  1,  1,  3,  5,  3,  1,  0,  1,  1,  6,  0,
        1,  0,  1,  2,  2,  2,  1,  1,  1,  0,  2,  1,  0,  1,  1,  0,  1,
        7,  5,  9,  4,  6, 15,  7,  3,  2,  8, 19, 10,  5,  6,  1,  1,  4,
        6,  5,  8,  7,  5,  7,  5,  5,  8, 11,  5,  4,  5,  4,  6,  6,  5,
        8,  7,  6,  3,  3,  1,  6,  7,  5,  7,  6,  6,  8,  5,  4,  8,  6,
       10,  6,  3,  5,  9,  8,  5,  2,  5,  6,  6,  6,  5,  9,  2,  5,  8,
        3,  8,  6,  9,  5,  6,  6,  8,  8,  5,  8,  4,  6,  6,  7,  6,  4,
        5,  2,  7, 19, 10,  8,  5,  5,  9,  4,  1,  7,  5, 10,  7,  8,  7,
        7,  7,  2,  6,  7,  6,  4,  9,  7,  5, 10,  5,  7,  5,  2,  4,  4,
        5,  8, 11,  5,  5

In [ ]:
y_preds_count2cls_values3 = np.array([y.item() for y in y_preds_count2cls3][1:])
y_preds_count2cls_values3

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0,
       0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 1, 0, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 1, 2, 1,
       1, 2, 2, 1, 2, 2, 2, 1, 2, 2, 3, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2,
       1, 3, 2, 3, 3, 3, 2, 3, 2, 3, 3, 3, 3, 3, 2, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 2])

## classification resnet 152

In [ ]:
from sklearn.metrics import confusion_matrix, classification_report

In [ ]:
## comparing class to y_pred class in resnet152
_, _, pre_se_sp_yi_report = report_precision_se_sp_yi(y_preds_values, y_true)
print(pre_se_sp_yi_report)

            Precision        SE        SP        YI
     class0    0.8440    0.8932    0.9096    0.8028
     class1    0.8217    0.8346    0.8598    0.6944
     class2    0.7692    0.5556    0.9765    0.5320
     class3    0.8519    0.9200    0.9850    0.9050
avg / total    0.8217    0.8009    0.9327    0.7335
              AVE_ACC           0.8282



In [ ]:
## comparing class to y_pred class in resnet152
print(confusion_matrix(y_true, y_preds_values))

[[ 92  11   0   0]
 [ 17 106   4   0]
 [  0  12  20   4]
 [  0   0   2  23]]


In [ ]:
## comparing class to count2cls in resnet 152
_, _, pre_se_sp_yi_report = report_precision_se_sp_yi(y_preds_values, y_preds_count2cls_values)
print(pre_se_sp_yi_report)

            Precision        SE        SP        YI
     class0    0.9450    1.0000    0.9681    0.9681
     class1    0.9922    0.9552    0.9936    0.9489
     class2    1.0000    0.9630    1.0000    0.9630
     class3    1.0000    1.0000    1.0000    1.0000
avg / total    0.9843    0.9795    0.9904    0.9700
              AVE_ACC           0.9759



In [ ]:
## comparing class to count2cls in resnet 152
print(confusion_matrix(y_preds_values, y_preds_count2cls_values))

[[103   6   0   0]
 [  0 128   1   0]
 [  0   0  26   0]
 [  0   0   0  27]]


## classification resnet 101


In [ ]:
## comparing class to y_pred class in resnet101
_, _, pre_se_sp_yi_report = report_precision_se_sp_yi(y_preds_values1, y_true)
print(pre_se_sp_yi_report)

            Precision        SE        SP        YI
     class0    0.7931    0.8932    0.8723    0.7655
     class1    0.7969    0.8031    0.8415    0.6446
     class2    0.8500    0.4722    0.9882    0.4605
     class3    0.8519    0.9200    0.9850    0.9050
avg / total    0.8230    0.7721    0.9218    0.6939
              AVE_ACC           0.8041



In [ ]:
## comparing class to y_pred class in resnet101
print(confusion_matrix(y_true, y_preds_values1))

[[ 92  11   0   0]
 [ 24 102   1   0]
 [  0  15  17   4]
 [  0   0   2  23]]


In [ ]:
## comparing class to count2cls in resnet 101
_, _, pre_se_sp_yi_report = report_precision_se_sp_yi(y_preds_values1, y_preds_count2cls_values1)
print(pre_se_sp_yi_report)

            Precision        SE        SP        YI
     class0    1.0000    0.9587    1.0000    0.9587
     class1    0.9531    1.0000    0.9645    0.9645
     class2    1.0000    0.9524    1.0000    0.9524
     class3    1.0000    1.0000    1.0000    1.0000
avg / total    0.9883    0.9778    0.9911    0.9689
              AVE_ACC           0.9794



In [ ]:
## comparing class to count2cls in resnet 101
print(confusion_matrix(y_preds_values1, y_preds_count2cls_values1))

[[116   0   0   0]
 [  5 122   1   0]
 [  0   0  20   0]
 [  0   0   0  27]]


## classification resnet 50

In [ ]:
## comparing class to y_pred class in resnet50
_, _, pre_se_sp_yi_report = report_precision_se_sp_yi(y_preds_values2, y_true)
print(pre_se_sp_yi_report)

            Precision        SE        SP        YI
     class0    0.8142    0.8932    0.8883    0.7815
     class1    0.8279    0.7953    0.8720    0.6672
     class2    0.7333    0.6111    0.9686    0.5797
     class3    0.8462    0.8800    0.9850    0.8650
avg / total    0.8054    0.7949    0.9285    0.7234
              AVE_ACC           0.8144



In [ ]:
## comparing class to y_pred class in resnet50
print(confusion_matrix(y_true, y_preds_values2))

[[ 92  11   0   0]
 [ 21 101   5   0]
 [  0  10  22   4]
 [  0   0   3  22]]


In [ ]:
## comparing class to count2cls in resnet 50
_, _, pre_se_sp_yi_report = report_precision_se_sp_yi(y_preds_values2, y_preds_count2cls_values2)
print(pre_se_sp_yi_report)

            Precision        SE        SP        YI
     class0    0.9646    0.9909    0.9779    0.9688
     class1    0.9672    0.9593    0.9762    0.9355
     class2    0.9333    0.9032    0.9923    0.8955
     class3    1.0000    0.9630    1.0000    0.9630
avg / total    0.9663    0.9541    0.9866    0.9407
              AVE_ACC           0.9656



In [ ]:
## comparing class to count2cls in resnet 50
print(confusion_matrix(y_preds_values2, y_preds_count2cls_values2))

[[109   4   0   0]
 [  1 118   3   0]
 [  0   1  28   1]
 [  0   0   0  26]]


## classification resnet 34

In [ ]:
## comparing class to y_pred class in resnet34
_, _, pre_se_sp_yi_report = report_precision_se_sp_yi(y_preds_values3, y_true)
print(pre_se_sp_yi_report)

            Precision        SE        SP        YI
     class0    0.7279    0.9612    0.8032    0.7644
     class1    0.8641    0.7008    0.9146    0.6154
     class2    0.7812    0.6944    0.9725    0.6670
     class3    0.9500    0.7600    0.9962    0.7562
avg / total    0.8308    0.7791    0.9217    0.7008
              AVE_ACC           0.7973



In [ ]:
## comparing class to y_pred class in resnet34
print(confusion_matrix(y_true, y_preds_values3))

[[99  4  0  0]
 [37 89  1  0]
 [ 0 10 25  1]
 [ 0  0  6 19]]


In [ ]:
## comparing class to count2cls in resnet 34
_, _, pre_se_sp_yi_report = report_precision_se_sp_yi(y_preds_values3, y_preds_count2cls_values3)
print(pre_se_sp_yi_report)

            Precision        SE        SP        YI
     class0    0.8971    1.0000    0.9172    0.9172
     class1    0.9806    0.8783    0.9886    0.8669
     class2    0.9375    0.9375    0.9923    0.9298
     class3    1.0000    0.9091    1.0000    0.9091
avg / total    0.9538    0.9312    0.9745    0.9057
              AVE_ACC           0.9381



In [ ]:
## comparing class to count2cls in resnet 34
print(confusion_matrix(y_preds_values3, y_preds_count2cls_values3))

[[122  14   0   0]
 [  0 101   2   0]
 [  0   0  30   2]
 [  0   0   0  20]]


# Make the DataFrame

In [ ]:
test_data_df

filename class counts
0     levle0_60.jpg     0      1
1    levle0_483.jpg     0      2
2    levle0_110.jpg     0      2
3    levle0_404.jpg     0      1
4    levle0_155.jpg     0      1
..              ...   ...    ...
286   levle3_83.jpg     3     51
287   levle3_37.jpg     3     55
288  levle3_109.jpg     3     52
289   levle3_76.jpg     3     56
290  levle3_113.jpg     3     64

[291 rows x 3 columns]

In [ ]:
test_data_df['y_preds_values152'] = y_preds_values.tolist()
test_data_df['y_preds_counts152'] = y_preds_count_values.tolist()
test_data_df['y_preds_count2cls152'] = y_preds_count2cls_values.tolist()
test_data_df['y_preds_values101'] = y_preds_values1.tolist()
test_data_df['y_preds_counts101'] = y_preds_count_values1.tolist()
test_data_df['y_preds_count2cls101'] = y_preds_count2cls_values1.tolist()
test_data_df['y_preds_values50'] = y_preds_values2.tolist()
test_data_df['y_preds_counts50'] = y_preds_count_values2.tolist()
test_data_df['y_preds_count2cls50'] = y_preds_count2cls_values2.tolist()
test_data_df['y_preds_values34'] = y_preds_values3.tolist()
test_data_df['y_preds_counts34'] = y_preds_count_values3.tolist()
test_data_df['y_preds_count2cls34'] = y_preds_count2cls_values3.tolist()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documen

In [ ]:
test_data_df

filename class counts  y_preds_values152  y_preds_counts152  \
0     levle0_60.jpg     0      1                  0                  2   
1    levle0_483.jpg     0      2                  0                  0   
2    levle0_110.jpg     0      2                  0                  0   
3    levle0_404.jpg     0      1                  0                  0   
4    levle0_155.jpg     0      1                  0                  1   
..              ...   ...    ...                ...                ...   
286   levle3_83.jpg     3     51                  3                 61   
287   levle3_37.jpg     3     55                  3                 60   
288  levle3_109.jpg     3     52                  3                 57   
289   levle3_76.jpg     3     56                  3                 53   
290  levle3_113.jpg     3     64                  3                 62   

     y_preds_count2cls152  y_preds_values101  y_preds_counts101  \
0                       0                  0                  2   
1                       0                  0                  0   
2                       0                  0                  0   
3                       0                  0                  1   
4                       0                  0                  1   
..                    ...                ...                ...   
286                     3                  3                 61   
287                     3                  3                 61   
288                     3                  3                 62   
289                     3                  3                 54   
290                     3                  3                 55   

     y_preds_count2cls101  y_preds_values50  y_preds_counts50  \
0                       0                 0                 3   
1                       0                 0                 0   
2                       0                 0                 1   
3                       0                 0                 0   
4                       0                 0                 3   
..                    ...               ...               ...   
286                     3                 3                61   
287                     3                 3                61   
288                     3                 3                63   
289                     3                 3                53   
290                     3                 3                54   

     y_preds_count2cls50  y_preds_values34  y_preds_counts34  \
0                      0                 0                 1   
1                      0                 0                 1   
2                      0                 0                 1   
3                      0                 0                 1   
4                      0                 0                 1   
..                   ...               ...               ...   
286                    3                 3                54   
287                    3                 3                55   
288                    3                 3                54   
289                    3                 3                60   
290                    3                 2                26   

     y_preds_count2cls34  
0                      0  
1                      0  
2                      0  
3                      0  
4                      0  
..                   ...  
286                    3  
287                    3  
288                    3  
289                    3  
290                    2  

[291 rows x 15 columns]

In [ ]:
test_data_df.dtypes

filename                object
class                   object
counts                  object
y_preds_values152        int64
y_preds_counts152        int64
y_preds_count2cls152     int64
y_preds_values101        int64
y_preds_counts101        int64
y_preds_count2cls101     int64
y_preds_values50         int64
y_preds_counts50         int64
y_preds_count2cls50      int64
y_preds_values34         int64
y_preds_counts34         int64
y_preds_count2cls34      int64
dtype: object

In [ ]:
test_data_df['class'] = test_data_df['class'].astype('int64')
test_data_df['counts'] = test_data_df['counts'].astype('int64')

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


In [ ]:
test_data_df.dtypes

filename                object
class                    int64
counts                   int64
y_preds_values152        int64
y_preds_counts152        int64
y_preds_count2cls152     int64
y_preds_values101        int64
y_preds_counts101        int64
y_preds_count2cls101     int64
y_preds_values50         int64
y_preds_counts50         int64
y_preds_count2cls50      int64
y_preds_values34         int64
y_preds_counts34         int64
y_preds_count2cls34      int64
dtype: object

## adding resnet 152 columns

In [ ]:
test_data_df['ycount152<true_counts'] = np.where(((test_data_df['counts']>test_data_df['y_preds_counts152']) & (test_data_df['class'] != test_data_df['y_preds_values152'])), test_data_df['filename'], np.nan)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [ ]:
images_lesser_counts_152 = test_data_df['ycount152<true_counts'].dropna().unique().tolist()
images_lesser_counts_152

['levle1_157.jpg',
 'levle1_212.jpg',
 'levle1_620.jpg',
 'levle1_526.jpg',
 'levle1_403.jpg',
 'levle1_103.jpg',
 'levle1_256.jpg',
 'levle1_121.jpg',
 'levle1_613.jpg',
 'levle1_179.jpg',
 'levle1_201.jpg',
 'levle1_269.jpg',
 'levle1_250.jpg',
 'levle1_554.jpg',
 'levle1_242.jpg',
 'levle1_494.jpg',
 'levle1_569.jpg',
 'levle2_26.jpg',
 'levle2_59.jpg',
 'levle2_108.jpg',
 'levle2_109.jpg',
 'levle2_40.jpg',
 'levle2_161.jpg',
 'levle2_190.jpg',
 'levle2_96.jpg',
 'levle3_64.jpg',
 'levle2_95.jpg',
 'levle2_56.jpg',
 'levle2_39.jpg',
 'levle3_117.jpg',
 'levle3_130.jpg']

In [ ]:
len(images_lesser_counts_152)

31

In [ ]:
test_data_df['count2cls152_!=_class152'] = np.where((test_data_df['y_preds_values152'] != test_data_df['y_preds_count2cls152']), test_data_df['filename'], np.nan)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [ ]:
images_unequal_class_152 = test_data_df['count2cls152_!=_class152'].dropna().unique().tolist()
images_unequal_class_152

['levle0_96.jpg',
 'levle0_173.jpg',
 'levle1_256.jpg',
 'levle1_201.jpg',
 'levle1_554.jpg',
 'levle1_494.jpg',
 'levle2_190.jpg']

In [ ]:
len(images_unequal_class_152)

7

In [ ]:
test_data_df['overall_lessthan_counts_152'] = np.where((test_data_df['counts']>test_data_df['y_preds_counts152']), test_data_df['filename'], np.nan)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [ ]:
overall_images_lesser_counts_152 = test_data_df['overall_lessthan_counts_152'].dropna().unique().tolist()
overall_images_lesser_counts_152

['levle0_483.jpg',
 'levle0_110.jpg',
 'levle0_404.jpg',
 'levle0_49.jpg',
 'levle0_216.jpg',
 'levle0_89.jpg',
 'levle0_172.jpg',
 'levle0_516.jpg',
 'levle0_81.jpg',
 'levle0_306.jpg',
 'levle0_20.jpg',
 'levle0_454.jpg',
 'levle0_229.jpg',
 'levle0_36.jpg',
 'levle0_17.jpg',
 'levle0_441.jpg',
 'levle0_518.jpg',
 'levle0_422.jpg',
 'levle0_48.jpg',
 'levle0_158.jpg',
 'levle0_367.jpg',
 'levle0_195.jpg',
 'levle0_351.jpg',
 'levle0_76.jpg',
 'levle0_530.jpg',
 'levle0_268.jpg',
 'levle0_462.jpg',
 'levle0_127.jpg',
 'levle0_239.jpg',
 'levle0_139.jpg',
 'levle0_136.jpg',
 'levle0_99.jpg',
 'levle0_474.jpg',
 'levle0_305.jpg',
 'levle0_391.jpg',
 'levle0_185.jpg',
 'levle1_379.jpg',
 'levle1_544.jpg',
 'levle0_24.jpg',
 'levle0_246.jpg',
 'levle0_146.jpg',
 'levle1_279.jpg',
 'levle0_514.jpg',
 'levle0_328.jpg',
 'levle0_394.jpg',
 'levle0_424.jpg',
 'levle0_55.jpg',
 'levle0_399.jpg',
 'levle0_330.jpg',
 'levle1_559.jpg',
 'levle0_152.jpg',
 'levle1_157.jpg',
 'levle1_612.jpg',
 'le

In [ ]:
len(overall_images_lesser_counts_152)

156

In [ ]:
test_data_df['ypred_!=_ytrue152'] = np.where((test_data_df['class'] != test_data_df['y_preds_values152']), test_data_df['filename'], np.nan)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [ ]:
images_unequal_predstrue_152 = test_data_df['ypred_!=_ytrue152'].dropna().unique().tolist()
images_unequal_predstrue_152

['levle0_329.jpg',
 'levle0_190.jpg',
 'levle0_45.jpg',
 'levle0_70.jpg',
 'levle0_198.jpg',
 'levle0_425.jpg',
 'levle0_413.jpg',
 'levle0_253.jpg',
 'levle0_232.jpg',
 'levle0_259.jpg',
 'levle0_157.jpg',
 'levle1_157.jpg',
 'levle1_212.jpg',
 'levle1_620.jpg',
 'levle1_526.jpg',
 'levle1_403.jpg',
 'levle1_100.jpg',
 'levle1_103.jpg',
 'levle1_256.jpg',
 'levle1_121.jpg',
 'levle1_366.jpg',
 'levle1_613.jpg',
 'levle1_179.jpg',
 'levle1_201.jpg',
 'levle1_398.jpg',
 'levle1_269.jpg',
 'levle1_250.jpg',
 'levle1_554.jpg',
 'levle1_242.jpg',
 'levle1_494.jpg',
 'levle1_569.jpg',
 'levle1_415.jpg',
 'levle2_94.jpg',
 'levle2_26.jpg',
 'levle2_59.jpg',
 'levle2_108.jpg',
 'levle2_109.jpg',
 'levle2_40.jpg',
 'levle2_161.jpg',
 'levle2_190.jpg',
 'levle2_96.jpg',
 'levle3_64.jpg',
 'levle2_95.jpg',
 'levle2_122.jpg',
 'levle2_35.jpg',
 'levle2_56.jpg',
 'levle2_39.jpg',
 'levle2_67.jpg',
 'levle3_117.jpg',
 'levle3_130.jpg']

In [ ]:
len(images_unequal_predstrue_152)

50

## adding resnet 101 columns

In [ ]:
test_data_df['ycount101<true_counts'] = np.where(((test_data_df['counts']>test_data_df['y_preds_counts101']) & (test_data_df['class'] != test_data_df['y_preds_values101'])), test_data_df['filename'], np.nan)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [ ]:
images_lesser_counts_101 = test_data_df['ycount101<true_counts'].dropna().unique().tolist()
images_lesser_counts_101

['levle1_157.jpg',
 'levle1_620.jpg',
 'levle1_176.jpg',
 'levle1_526.jpg',
 'levle1_403.jpg',
 'levle1_414.jpg',
 'levle1_207.jpg',
 'levle1_514.jpg',
 'levle1_256.jpg',
 'levle1_121.jpg',
 'levle1_594.jpg',
 'levle1_582.jpg',
 'levle1_179.jpg',
 'levle1_201.jpg',
 'levle1_269.jpg',
 'levle1_274.jpg',
 'levle1_287.jpg',
 'levle1_250.jpg',
 'levle1_554.jpg',
 'levle1_315.jpg',
 'levle1_242.jpg',
 'levle1_135.jpg',
 'levle1_494.jpg',
 'levle1_569.jpg',
 'levle2_78.jpg',
 'levle2_26.jpg',
 'levle2_59.jpg',
 'levle2_108.jpg',
 'levle2_109.jpg',
 'levle2_40.jpg',
 'levle2_161.jpg',
 'levle2_190.jpg',
 'levle2_96.jpg',
 'levle3_64.jpg',
 'levle2_95.jpg',
 'levle2_11.jpg',
 'levle2_49.jpg',
 'levle2_56.jpg',
 'levle2_39.jpg',
 'levle3_110.jpg',
 'levle3_117.jpg']

In [ ]:
len(images_lesser_counts_101)

41

In [ ]:
test_data_df['count2cls101_!=_class101'] = np.where((test_data_df['y_preds_values101'] != test_data_df['y_preds_count2cls101']), test_data_df['filename'], np.nan)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [ ]:
images_unequal_class_101 = test_data_df['count2cls101_!=_class101'].dropna().unique().tolist()
images_unequal_class_101

['levle0_396.jpg',
 'levle1_212.jpg',
 'levle1_59.jpg',
 'levle1_302.jpg',
 'levle1_248.jpg',
 'levle2_11.jpg']

In [ ]:
len(images_unequal_class_101)

6

In [ ]:
test_data_df['overall_lessthan_counts_101'] = np.where((test_data_df['counts']>test_data_df['y_preds_counts101']), test_data_df['filename'], np.nan)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [ ]:
overall_images_lesser_counts_101 = test_data_df['overall_lessthan_counts_101'].dropna().unique().tolist()
overall_images_lesser_counts_101

['levle0_483.jpg',
 'levle0_110.jpg',
 'levle0_49.jpg',
 'levle0_113.jpg',
 'levle0_216.jpg',
 'levle0_172.jpg',
 'levle0_160.jpg',
 'levle0_516.jpg',
 'levle0_70.jpg',
 'levle0_81.jpg',
 'levle0_20.jpg',
 'levle0_454.jpg',
 'levle0_229.jpg',
 'levle0_36.jpg',
 'levle0_87.jpg',
 'levle0_17.jpg',
 'levle0_441.jpg',
 'levle0_518.jpg',
 'levle0_422.jpg',
 'levle0_48.jpg',
 'levle0_158.jpg',
 'levle0_367.jpg',
 'levle0_116.jpg',
 'levle0_244.jpg',
 'levle0_351.jpg',
 'levle0_76.jpg',
 'levle0_530.jpg',
 'levle0_268.jpg',
 'levle0_526.jpg',
 'levle0_462.jpg',
 'levle0_127.jpg',
 'levle0_239.jpg',
 'levle0_139.jpg',
 'levle0_463.jpg',
 'levle0_99.jpg',
 'levle0_474.jpg',
 'levle0_305.jpg',
 'levle0_391.jpg',
 'levle0_185.jpg',
 'levle1_379.jpg',
 'levle0_443.jpg',
 'levle1_544.jpg',
 'levle0_524.jpg',
 'levle0_24.jpg',
 'levle0_246.jpg',
 'levle0_146.jpg',
 'levle1_279.jpg',
 'levle0_514.jpg',
 'levle0_328.jpg',
 'levle0_92.jpg',
 'levle0_424.jpg',
 'levle0_55.jpg',
 'levle0_399.jpg',
 'levl

In [ ]:
len(overall_images_lesser_counts_101)

168

In [ ]:
test_data_df['ypred_!=_ytrue101'] = np.where((test_data_df['class'] != test_data_df['y_preds_values101']), test_data_df['filename'], np.nan)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [ ]:
images_unequal_predstrue_101 = test_data_df['ypred_!=_ytrue101'].dropna().unique().tolist()
images_unequal_predstrue_101

['levle0_329.jpg',
 'levle0_190.jpg',
 'levle0_45.jpg',
 'levle0_198.jpg',
 'levle0_425.jpg',
 'levle0_209.jpg',
 'levle0_413.jpg',
 'levle0_253.jpg',
 'levle0_396.jpg',
 'levle0_259.jpg',
 'levle0_157.jpg',
 'levle1_157.jpg',
 'levle1_620.jpg',
 'levle1_176.jpg',
 'levle1_526.jpg',
 'levle1_403.jpg',
 'levle1_414.jpg',
 'levle1_207.jpg',
 'levle1_514.jpg',
 'levle1_256.jpg',
 'levle1_121.jpg',
 'levle1_594.jpg',
 'levle1_582.jpg',
 'levle1_179.jpg',
 'levle1_201.jpg',
 'levle1_269.jpg',
 'levle1_274.jpg',
 'levle1_287.jpg',
 'levle1_250.jpg',
 'levle1_554.jpg',
 'levle1_315.jpg',
 'levle1_242.jpg',
 'levle1_135.jpg',
 'levle1_494.jpg',
 'levle1_569.jpg',
 'levle1_415.jpg',
 'levle2_78.jpg',
 'levle2_94.jpg',
 'levle2_26.jpg',
 'levle2_59.jpg',
 'levle2_108.jpg',
 'levle2_109.jpg',
 'levle2_40.jpg',
 'levle2_161.jpg',
 'levle2_190.jpg',
 'levle2_96.jpg',
 'levle3_64.jpg',
 'levle2_95.jpg',
 'levle2_122.jpg',
 'levle2_11.jpg',
 'levle2_49.jpg',
 'levle2_35.jpg',
 'levle2_56.jpg',
 'levl

In [ ]:
len(images_unequal_predstrue_101)

57

## adding resnet 50 columns

In [ ]:
test_data_df['ycount50<true_counts'] = np.where(((test_data_df['counts']>test_data_df['y_preds_counts50']) & (test_data_df['class'] != test_data_df['y_preds_values50'])), test_data_df['filename'], np.nan)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [ ]:
images_lesser_counts_50 = test_data_df['ycount50<true_counts'].dropna().unique().tolist()
images_lesser_counts_50

['levle1_157.jpg',
 'levle1_212.jpg',
 'levle1_620.jpg',
 'levle1_526.jpg',
 'levle1_403.jpg',
 'levle1_414.jpg',
 'levle1_121.jpg',
 'levle1_348.jpg',
 'levle1_302.jpg',
 'levle1_613.jpg',
 'levle1_179.jpg',
 'levle1_269.jpg',
 'levle1_274.jpg',
 'levle1_287.jpg',
 'levle1_250.jpg',
 'levle1_554.jpg',
 'levle1_283.jpg',
 'levle1_337.jpg',
 'levle1_242.jpg',
 'levle1_135.jpg',
 'levle1_569.jpg',
 'levle2_78.jpg',
 'levle2_26.jpg',
 'levle2_59.jpg',
 'levle2_40.jpg',
 'levle2_96.jpg',
 'levle3_64.jpg',
 'levle2_95.jpg',
 'levle2_49.jpg',
 'levle2_56.jpg',
 'levle2_39.jpg',
 'levle3_110.jpg',
 'levle3_66.jpg']

In [ ]:
len(images_lesser_counts_50)

33

In [ ]:
test_data_df['count2cls50_!=_class50'] = np.where((test_data_df['y_preds_values50'] != test_data_df['y_preds_count2cls50']), test_data_df['filename'], np.nan)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [ ]:
images_unequal_class_50 = test_data_df['count2cls50_!=_class50'].dropna().unique().tolist()
images_unequal_class_50

['levle0_70.jpg',
 'levle0_524.jpg',
 'levle0_393.jpg',
 'levle1_59.jpg',
 'levle1_337.jpg',
 'levle2_26.jpg',
 'levle3_90.jpg',
 'levle2_96.jpg',
 'levle2_56.jpg',
 'levle3_117.jpg']

In [ ]:
len(images_unequal_class_50)

10

In [ ]:
test_data_df['overall_lessthan_counts_50'] = np.where((test_data_df['counts']>test_data_df['y_preds_counts50']), test_data_df['filename'], np.nan)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [ ]:
overall_images_lesser_counts_50 = test_data_df['overall_lessthan_counts_50'].dropna().unique().tolist()
overall_images_lesser_counts_50

['levle0_483.jpg',
 'levle0_110.jpg',
 'levle0_404.jpg',
 'levle0_49.jpg',
 'levle0_216.jpg',
 'levle0_172.jpg',
 'levle0_160.jpg',
 'levle0_516.jpg',
 'levle0_81.jpg',
 'levle0_306.jpg',
 'levle0_20.jpg',
 'levle0_454.jpg',
 'levle0_229.jpg',
 'levle0_36.jpg',
 'levle0_17.jpg',
 'levle0_441.jpg',
 'levle0_518.jpg',
 'levle0_48.jpg',
 'levle0_158.jpg',
 'levle0_367.jpg',
 'levle0_244.jpg',
 'levle0_76.jpg',
 'levle0_530.jpg',
 'levle0_268.jpg',
 'levle0_526.jpg',
 'levle0_462.jpg',
 'levle0_127.jpg',
 'levle0_239.jpg',
 'levle0_139.jpg',
 'levle0_463.jpg',
 'levle0_99.jpg',
 'levle0_474.jpg',
 'levle0_374.jpg',
 'levle0_305.jpg',
 'levle0_391.jpg',
 'levle0_185.jpg',
 'levle1_379.jpg',
 'levle1_544.jpg',
 'levle0_24.jpg',
 'levle0_246.jpg',
 'levle0_146.jpg',
 'levle0_514.jpg',
 'levle0_424.jpg',
 'levle0_55.jpg',
 'levle0_399.jpg',
 'levle0_330.jpg',
 'levle1_559.jpg',
 'levle1_157.jpg',
 'levle1_612.jpg',
 'levle1_297.jpg',
 'levle1_590.jpg',
 'levle1_212.jpg',
 'levle1_620.jpg',
 'l

In [ ]:
len(overall_images_lesser_counts_50)

153

In [ ]:
test_data_df['ypred_!=_ytrue50'] = np.where((test_data_df['class'] != test_data_df['y_preds_values50']), test_data_df['filename'], np.nan)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [ ]:
images_unequal_predstrue_50 = test_data_df['ypred_!=_ytrue50'].dropna().unique().tolist()
images_unequal_predstrue_50

['levle0_329.jpg',
 'levle0_190.jpg',
 'levle0_162.jpg',
 'levle0_425.jpg',
 'levle0_413.jpg',
 'levle0_256.jpg',
 'levle0_253.jpg',
 'levle0_232.jpg',
 'levle0_396.jpg',
 'levle0_259.jpg',
 'levle0_157.jpg',
 'levle1_157.jpg',
 'levle1_212.jpg',
 'levle1_620.jpg',
 'levle1_38.jpg',
 'levle1_526.jpg',
 'levle1_403.jpg',
 'levle1_414.jpg',
 'levle1_121.jpg',
 'levle1_348.jpg',
 'levle1_302.jpg',
 'levle1_613.jpg',
 'levle1_179.jpg',
 'levle1_269.jpg',
 'levle1_274.jpg',
 'levle1_231.jpg',
 'levle1_262.jpg',
 'levle1_287.jpg',
 'levle1_250.jpg',
 'levle1_554.jpg',
 'levle1_283.jpg',
 'levle1_261.jpg',
 'levle1_337.jpg',
 'levle1_242.jpg',
 'levle1_135.jpg',
 'levle1_569.jpg',
 'levle1_415.jpg',
 'levle2_78.jpg',
 'levle2_94.jpg',
 'levle2_26.jpg',
 'levle2_59.jpg',
 'levle2_40.jpg',
 'levle2_96.jpg',
 'levle3_64.jpg',
 'levle2_95.jpg',
 'levle2_122.jpg',
 'levle2_49.jpg',
 'levle2_35.jpg',
 'levle2_56.jpg',
 'levle2_39.jpg',
 'levle2_67.jpg',
 'levle3_110.jpg',
 'levle3_66.jpg',
 'levle3

In [ ]:
len(images_unequal_predstrue_50)

54

## adding resnet 34 columns

In [ ]:
test_data_df['ycount34<true_counts'] = np.where(((test_data_df['counts']>test_data_df['y_preds_counts34']) & (test_data_df['class'] != test_data_df['y_preds_values34'])), test_data_df['filename'], np.nan)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [ ]:
images_lesser_counts_34 = test_data_df['ycount34<true_counts'].dropna().unique().tolist()
images_lesser_counts_34

['levle1_157.jpg',
 'levle1_212.jpg',
 'levle1_620.jpg',
 'levle1_176.jpg',
 'levle1_526.jpg',
 'levle1_403.jpg',
 'levle1_414.jpg',
 'levle1_349.jpg',
 'levle1_207.jpg',
 'levle1_639.jpg',
 'levle1_59.jpg',
 'levle1_321.jpg',
 'levle1_43.jpg',
 'levle1_256.jpg',
 'levle1_121.jpg',
 'levle1_5.jpg',
 'levle1_348.jpg',
 'levle1_302.jpg',
 'levle1_613.jpg',
 'levle1_560.jpg',
 'levle1_594.jpg',
 'levle1_582.jpg',
 'levle1_201.jpg',
 'levle1_12.jpg',
 'levle1_274.jpg',
 'levle1_287.jpg',
 'levle1_364.jpg',
 'levle1_250.jpg',
 'levle1_554.jpg',
 'levle1_283.jpg',
 'levle1_315.jpg',
 'levle1_35.jpg',
 'levle1_242.jpg',
 'levle1_483.jpg',
 'levle1_135.jpg',
 'levle1_595.jpg',
 'levle1_569.jpg',
 'levle2_108.jpg',
 'levle2_40.jpg',
 'levle2_170.jpg',
 'levle2_157.jpg',
 'levle2_190.jpg',
 'levle3_64.jpg',
 'levle2_49.jpg',
 'levle2_83.jpg',
 'levle2_39.jpg',
 'levle3_110.jpg',
 'levle3_94.jpg',
 'levle3_117.jpg',
 'levle3_130.jpg',
 'levle3_113.jpg']

In [ ]:
len(images_lesser_counts_34)

51

In [ ]:
test_data_df['count2cls34_!=_class34'] = np.where((test_data_df['y_preds_values34'] != test_data_df['y_preds_count2cls34']), test_data_df['filename'], np.nan)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [ ]:
images_unequal_class_34 = test_data_df['count2cls34_!=_class34'].dropna().unique().tolist()
images_unequal_class_34

['levle0_198.jpg',
 'levle0_425.jpg',
 'levle0_232.jpg',
 'levle1_176.jpg',
 'levle1_349.jpg',
 'levle1_207.jpg',
 'levle1_59.jpg',
 'levle1_5.jpg',
 'levle1_287.jpg',
 'levle1_364.jpg',
 'levle1_283.jpg',
 'levle1_315.jpg',
 'levle1_35.jpg',
 'levle1_595.jpg',
 'levle2_95.jpg',
 'levle2_122.jpg',
 'levle2_83.jpg',
 'levle3_126.jpg']

In [ ]:
len(images_unequal_class_34)

18

In [ ]:
test_data_df['overall_lessthan_counts_34'] = np.where((test_data_df['counts']>test_data_df['y_preds_counts34']), test_data_df['filename'], np.nan)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [ ]:
overall_images_lesser_counts_34 = test_data_df['overall_lessthan_counts_34'].dropna().unique().tolist()
overall_images_lesser_counts_34

['levle0_483.jpg',
 'levle0_110.jpg',
 'levle0_49.jpg',
 'levle0_216.jpg',
 'levle0_172.jpg',
 'levle0_160.jpg',
 'levle0_516.jpg',
 'levle0_81.jpg',
 'levle0_306.jpg',
 'levle0_20.jpg',
 'levle0_454.jpg',
 'levle0_229.jpg',
 'levle0_36.jpg',
 'levle0_87.jpg',
 'levle0_17.jpg',
 'levle0_441.jpg',
 'levle0_518.jpg',
 'levle0_422.jpg',
 'levle0_48.jpg',
 'levle0_158.jpg',
 'levle0_367.jpg',
 'levle0_195.jpg',
 'levle0_116.jpg',
 'levle0_244.jpg',
 'levle0_76.jpg',
 'levle0_530.jpg',
 'levle0_268.jpg',
 'levle0_526.jpg',
 'levle0_462.jpg',
 'levle0_127.jpg',
 'levle0_239.jpg',
 'levle0_139.jpg',
 'levle0_260.jpg',
 'levle0_463.jpg',
 'levle0_99.jpg',
 'levle0_474.jpg',
 'levle0_305.jpg',
 'levle0_391.jpg',
 'levle0_185.jpg',
 'levle1_379.jpg',
 'levle0_443.jpg',
 'levle0_524.jpg',
 'levle0_24.jpg',
 'levle0_246.jpg',
 'levle0_146.jpg',
 'levle1_279.jpg',
 'levle0_514.jpg',
 'levle0_230.jpg',
 'levle0_92.jpg',
 'levle0_424.jpg',
 'levle0_55.jpg',
 'levle0_316.jpg',
 'levle0_399.jpg',
 'lev

In [ ]:
len(overall_images_lesser_counts_34)

185

In [ ]:
test_data_df['ypred_!=_ytrue34'] = np.where((test_data_df['class'] != test_data_df['y_preds_values34']), test_data_df['filename'], np.nan)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [ ]:
images_unequal_predstrue_34 = test_data_df['ypred_!=_ytrue34'].dropna().unique().tolist()
images_unequal_predstrue_34

['levle0_190.jpg',
 'levle0_253.jpg',
 'levle0_396.jpg',
 'levle0_157.jpg',
 'levle1_157.jpg',
 'levle1_212.jpg',
 'levle1_620.jpg',
 'levle1_176.jpg',
 'levle1_526.jpg',
 'levle1_403.jpg',
 'levle1_414.jpg',
 'levle1_349.jpg',
 'levle1_207.jpg',
 'levle1_639.jpg',
 'levle1_59.jpg',
 'levle1_321.jpg',
 'levle1_43.jpg',
 'levle1_256.jpg',
 'levle1_121.jpg',
 'levle1_5.jpg',
 'levle1_348.jpg',
 'levle1_302.jpg',
 'levle1_613.jpg',
 'levle1_560.jpg',
 'levle1_594.jpg',
 'levle1_582.jpg',
 'levle1_201.jpg',
 'levle1_12.jpg',
 'levle1_274.jpg',
 'levle1_287.jpg',
 'levle1_364.jpg',
 'levle1_250.jpg',
 'levle1_554.jpg',
 'levle1_283.jpg',
 'levle1_315.jpg',
 'levle1_35.jpg',
 'levle1_242.jpg',
 'levle1_483.jpg',
 'levle1_135.jpg',
 'levle1_595.jpg',
 'levle1_569.jpg',
 'levle1_415.jpg',
 'levle2_108.jpg',
 'levle2_40.jpg',
 'levle2_170.jpg',
 'levle2_157.jpg',
 'levle2_190.jpg',
 'levle3_64.jpg',
 'levle2_95.jpg',
 'levle2_49.jpg',
 'levle2_83.jpg',
 'levle2_39.jpg',
 'levle2_67.jpg',
 'levl

In [ ]:
len(images_unequal_predstrue_34)

59